[package]
name = "poc"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.21" # 提供 Stream trait
yamux = "0.13"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "io-util", "macros", "net", "fs", "time" ] } # 异步网络库
tokio-util = { version = "0.7", features = ["codec", "compat"] }
anyhow = "1.0.98"

